spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.137.101:3306/ctlinfo
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 80
